# Generated by Django 5.1.3 on 2024-12-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_companytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=30)),
            ],
        ),
    ]
