# Generated by Django 5.1.3 on 2024-12-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_company',
        ),
    ]
