from django.urls import path
from Admin import views
app_name="Admin"
urlpatterns = [
   path('add/',views.add,name='add'),
   path('largest/',views.largest,name='largest'),
   path('calculator/',views.calculator,name='calculator'),
   path('Register/',views.Register,name='Register'),
   path('District/',views.District,name='District'),
   path('category/',views.category,name='category'),
   path('delcategory/<int:id>', views.delcategory, name='delcategory'),
   path('editcategory/<int:id>', views.editcategory, name='editcategory'),
   path('deldistrict/<int:id>', views.deldistrict, name='deldistrict'),
   path('editdistrict/<int:id>', views.editdistrict, name='editdistrict'),
   path('admin/',views.admin,name='admin'),
   path('deladmin/<int:id>',views.deladmin,name='deladmin'),
   path('editadmin/<int:id>',views.editadmin,name='editadmin'),
   path('place/',views.place,name='place'),
   path('editplace/<int:id>',views.editplace,name='editplace'),
   path('delplace/<int:id>',views.delplace,name='delplace'),
   path('subcategory',views.subcategory,name='subcategory'),
   path('editsubcategory/<int:id>',views.editsubcategory,name='editsubcategory'),
   path('delsubcategory/<int:id>',views.delsubcategory,name='delsubcategory'),
   path('UserVerification/',views.UserVerification,name='UserVerification'),
   path('userreject/<int:id>',views.userreject,name='userreject'),
   path('Product/',views.Product,name='Product'),
   path('ajaxcategory/',views.ajaxcategory,name='ajaxcategory'),
   path('Companytype/',views.Companytype,name='Companytype'),
   path('delcompanytype/<int:id>',views.delcompanytype,name='delcompanytype'),
   path('Viewcompany/',views.Viewcompany,name='Viewcompany'),
   path('companyaccept/<int:id>',views.companyaccept,name='companyaccept'),
   path('companyreject/<int:id>',views.companyreject,name='companyreject'),
   path('Acceptedcompany/',views.Acceptedcompany,name='Acceptedcompany'),  
   path('Rejectedcompany/',views.Rejectedcompany,name='Rejectedcompany'),
   path('Adminhome/',views.Adminhome,name='Adminhome'),
   path('Header/',views.Header,name='Header'),
   path('Jobtype/',views.Jobtype,name='Jobtype'),
   path('Jobgroup/',views.Jobgroup,name='Jobgroup'),
   path('deljobtype/<int:id>',views.deljobtype,name='deljobtype'),
   path('Materials/',views.Materials,name='Materials'),
   path('delmaterial/<int:id>',views.delmaterial,name='delmaterial'),
   path('Viewfeedback/',views.Viewfeedback,name='Viewfeedback'),
   path('Viewcomplaint/',views.Viewcomplaint,name='Viewcomplaint'),
   path('replay/<int:id>',views.replay,name='replay'),
   path('Rcomplaint/',views.Rcomplaint,name='Rcomplaint'),
   path('logout/',views.logout,name='logout'),
   path('subpeople/',views.subpeople,name='subpeople'),
   path('adminreport/',views.adminreport,name='adminreport'),
   path('Rejectcompany/<int:id>',views.Rejectcompany,name='Rejectcompany'),
   path('chart-data/',views.get_chart_data, name='get_chart_data'),



]