# Generated by Django 5.1.3 on 2024-12-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_jobtype',
            old_name='job_name',
            new_name='job_type',
        ),
    ]
