# Generated by Django 5.1.3 on 2024-12-18 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_rename_job_name_tbl_jobtype_job_type'),
        ('Guest', '0005_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=40)),
                ('job_details', models.CharField(max_length=50)),
                ('job_date', models.DateField(auto_now_add=True)),
                ('job_lastdate', models.DateField()),
                ('job_qualification', models.CharField(max_length=50)),
                ('job_status', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_jobtype')),
            ],
        ),
    ]
