# Generated by Django 5.1.3 on 2024-12-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_tbl_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_job',
        ),
    ]
