# Generated by Django 5.1.3 on 2024-12-19 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_tbl_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_file', models.FileField(upload_to='Assets/Admin/Materials/')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_jobtype')),
            ],
        ),
    ]
