# Generated by Django 5.1.4 on 2025-01-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_tbl_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
