# Generated by Django 5.1.4 on 2025-01-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0009_tbl_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_rating',
            name='user',
        ),
    ]
