# Generated by Django 5.1.4 on 2025-01-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_remove_tbl_rating_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
