# Generated by Django 5.1.4 on 2025-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_remove_tbl_rating_company_remove_tbl_rating_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=40)),
                ('job_details', models.CharField(max_length=50)),
                ('job_date', models.DateField(auto_now_add=True)),
                ('job_lastdate', models.DateField()),
                ('job_qualification', models.CharField(max_length=50)),
                ('job_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_data', models.IntegerField()),
                ('user_review', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
