# Generated by Django 5.1.4 on 2025-01-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0014_tbl_job_tbl_rating'),
        ('Guest', '0009_tbl_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company'),
        ),
        migrations.AddField(
            model_name='tbl_job',
            name='jobtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_jobtype'),
        ),
        migrations.AddField(
            model_name='tbl_rating',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company'),
        ),
        migrations.AddField(
            model_name='tbl_rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
