# Generated by Django 5.1.4 on 2025-01-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_tbl_job_company_tbl_job_jobtype_tbl_rating_company_and_more'),
        ('User', '0010_delete_tbl_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_job',
        ),
    ]
