# Generated by Django 5.1.4 on 2025-01-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0016_delete_tbl_job'),
        ('Guest', '0011_tbl_company_interview_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=40)),
                ('job_details', models.CharField(max_length=50)),
                ('job_date', models.DateField(auto_now_add=True)),
                ('job_lastdate', models.DateField()),
                ('job_qualification', models.CharField(max_length=50)),
                ('job_status', models.CharField(max_length=50)),
                ('job_salary', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_jobtype')),
            ],
        ),
    ]
