# Generated by Django 5.1.5 on 2025-02-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_tbl_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_jobgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_group', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_job',
            name='job_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_job',
            name='jobgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_jobgroup'),
        ),
    ]
