# Generated by Django 5.1.5 on 2025-02-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0018_tbl_jobgroup_alter_tbl_job_job_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_materials',
        ),
    ]
