# Generated by Django 5.1.5 on 2025-02-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_delete_tbl_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_file', models.FileField(upload_to='Assets/Admin/Materials/')),
                ('jobgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_jobtype')),
            ],
        ),
    ]
