# Generated by Django 5.1.5 on 2025-02-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0020_tbl_materials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_materials',
        ),
    ]
