# Generated by Django 5.1.3 on 2024-12-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
