# Generated by Django 5.1.4 on 2025-01-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_paystatus',
            field=models.IntegerField(default=0),
        ),
    ]
