# Generated by Django 5.1.4 on 2025-01-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_user_user_paystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company',
            name='interview_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
