# Generated by Django 5.1.4 on 2025-01-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_remove_tbl_rating_company_remove_tbl_rating_user_and_more'),
        ('Guest', '0007_tbl_company_interview_link'),
        ('User', '0008_remove_tbl_request_job_remove_tbl_request_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_company',
        ),
    ]
