# Generated by Django 5.1.4 on 2025-01-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_delete_tbl_company'),
        ('Guest', '0008_delete_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_email', models.CharField(max_length=50)),
                ('company_contact', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=60)),
                ('company_password', models.CharField(max_length=50)),
                ('company_logo', models.FileField(upload_to='Assets/Admin/logos/')),
                ('company_licence', models.FileField(upload_to='Assets/Admin/licences/')),
                ('company_status', models.IntegerField(default=0)),
                ('interview_link', models.CharField(max_length=250, null=True)),
                ('companytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_companytype')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
