# Generated by Django 5.1.4 on 2025-01-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_company',
            name='interview_link',
        ),
    ]
