# Generated by Django 5.1.4 on 2025-01-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_remove_tbl_company_interview_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company',
            name='interview_link',
            field=models.URLField(null=True),
        ),
    ]
