# Generated by Django 5.1.5 on 2025-02-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_company_interview_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
