# Generated by Django 5.1.5 on 2025-03-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
