# Generated by Django 5.1.3 on 2024-12-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_user'),
        ('User', '0003_tbl_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaints',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company'),
        ),
        migrations.AlterField(
            model_name='tbl_complaints',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
