# Generated by Django 5.1.3 on 2024-12-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_complaints_company_alter_tbl_complaints_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaints',
        ),
    ]
