# Generated by Django 5.1.3 on 2024-12-21 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_user'),
        ('User', '0005_delete_tbl_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_content', models.CharField(max_length=50)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_status', models.IntegerField(default=0)),
                ('compalint_replay', models.CharField(max_length=60)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
