# Generated by Django 5.1.4 on 2025-01-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_request',
            name='job',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_complaints',
        ),
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
