# Generated by Django 5.1.5 on 2025-02-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_tbl_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complaints',
            old_name='compalint_replay',
            new_name='complaint_replay',
        ),
    ]
